name: Build and deploy Python project to Azure Function App - rag-demo-mb

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install packages into deploy folder
        run: |
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_83A02592801E4A7EB663A873DCC2E752 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8F10E164C53E4DBDB1C21FD5AF8A2E4E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B47593E3D7194F689CBE9A4B9D770998 }}

      - uses: Azure/functions-action@v1
        with:
          app-name: rag-demo-mb
          package: .
